# Generated by Django 3.0.8 on 2020-08-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CdiPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('trade_price', models.DecimalField(decimal_places=16, max_digits=19)),
            ],
        ),
        migrations.AddConstraint(
            model_name='cdiprice',
            constraint=models.UniqueConstraint(fields=('date', 'trade_price'), name='unique_cdi_price'),
        ),
    ]
